language: ruby

rvm:
  - 2.1

script: bundle exec jekyll build && bundle exec htmlproofer --disable-external --allow-hash-href ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
