language: ruby

rvm:
  - 2.1

script: bundle exec jekyll build && bundle exec htmlproof --href-ignore '#,/linkedin\.com/' ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
