name:      Ismael Ambrosi
sub_title: Estaba aburrido y me armé un blog.
url:       http://iambrosi.github.io

permalink:   /blog/:year/:month/:day/:title/
highlighter: pygments
markdown:    redcarpet
include:     [_pages]
exclude:     [ README.md, Gemfile, vendor ]

me:
  name:      Ismael Ambrosi
  email:     ismaambrosi@gmail.com
  github:    iambrosi
  linkedin:  ismaelambrosi
  twitter:   iambrosi
  instagram: iambrosi
  gravatar:  1fe25dce85a62c717339dfd864b16a92

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      lang: es
  -
    scope:
      path: _posts/es
    values:
      layout: default
      lang: es
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _pages/en
    values:
      lang: en
