name:      Ismael Ambrosi
sub_title: Estaba aburrido y me armé un blog.
url:       http://iambrosi.github.io

safe:        true
permalink:   /blog/:year/:month/:day/:title/
highlighter: pygments
markdown:    redcarpet
exclude:     [ README.md, Gemfile ]

me:
  name:      Ismael Ambrosi
  email:     ismaambrosi@gmail.com
  github:    iambrosi
  linkedin:  ismaelambrosi
  twitter:   iambrosi
  instagram: iambrosi
  gravatar:  1fe25dce85a62c717339dfd864b16a92

defaults:
  -
    scope:
      path: _posts/es
    values:
      layout: default
      lang: es
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
